name: build for github pages by parcel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: elm install
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install elm

      - name: yarn install
        uses: nuxt/actions-yarn@master
        with:
          args: "install"

      - name: yarn build
        uses: nuxt/actions-yarn@master
        with:
          args: "build-github-pages"

      - name: publish github pages
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: publish_gh_pages
          publish_dir: docs
